config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root "home#index"

  resources :recipes do
    resources :steps do
    end
    collection do 
      get :add_ingredient
      get :add_step
    end
  end

  resources :ingredients
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/ingredient.rb
class Ingredient < ApplicationRecord
  has_many :recipes, through: :ingredients_lists
  has_many :ingredients_lists
  accepts_nested_attributes_for :ingredients_lists
  validates :name, presence: true
end

app/models/ingredients_list.rb
class IngredientsList < ApplicationRecord
  belongs_to :ingredient
  belongs_to :recipe
end

app/models/recipe.rb
class Recipe < ApplicationRecord
  mount_uploader :image, ImageUploader
  
  has_many :steps, dependent: :destroy
  has_many :ingredients_lists, dependent: :destroy
  has_many :ingredients, through: :ingredients_lists
  belongs_to :user

  accepts_nested_attributes_for :steps
  accepts_nested_attributes_for :ingredients
  accepts_nested_attributes_for :ingredients_lists

  validates :name, :description, presence: true
  validates :image, :description, presence: true
  validates :time, :quantity, presence:true, numericality: { only_integer: true, greater_than: 0 }
end

app/models/step.rb
class Step < ApplicationRecord
  mount_uploader :image, ImageUploader
  belongs_to :recipe

  validates :sequence, :description, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  mount_uploader :image, ImageUploader

  has_many :recipes
  has_many :steps, :through => :recipes

  validates :email, format: { with: /\A[^@\s]+@[^@\s]+\z/ }, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

    def index

    end
    private

end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  def index
    @recipes = Recipe.all
  end
end

app/controllers/ingredients_controller.rb
class IngredientsController < ApplicationController

  def index
    @ingredients = Ingredient.all
  end

  def new
    @ingredient = Ingredient.new
  end

  def create
    @ingredient = Ingredient.new(ingredient_params)
    byebug
    if @ingredient.save
      redirect_to root_path
    else
      render :new
    end
  end

  def edit
    @ingredient = Ingredient.all.find(params[:id])
  end

  def update
    ingredient = Ingredient.all.find(params[:id])

    if ingredient.update(ingredient_params)
      redirect_to root_path
    else
      render :edit
    end
  end

  def destroy
    ingredient = Ingredient.all.find(param[:id])
    ingredient.destroy
    redirect_to root_path
  end



  private

  def ingredient_params
    params.require(:ingredient).permit(
                                        :name
                                      )
  end
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  layout 'homepage'
  def index
    @recipes = current_user.recipes.all
  end

  def new
    @recipe = Recipe.new
    @recipe.steps.new("sequence" => "1")
    ingredient = @recipe.ingredients.new
    ingredient.ingredients_lists.new
  end

  def create
    list_params = pick_ingredients_lists_params
    fixed_params = delete_list_params(recipe_params)
  
    @recipe = current_user.recipes.build(fixed_params)

    if @recipe.save
      set_all_ingredient_amount(@recipe, list_params)
      redirect_to recipes_path
    else
      render :new, notice: "似乎有那裡不對勁"
    end
  end

  def show
    @recipe = Recipe.find(params[:id])
    @ingredients_lists = @recipe.ingredients_lists
  end

  def destroy
    @recipe = current_user.recipes.find(params[:id])
    @recipe.destroy
    redirect_to recipes_path
  end
  
  def edit
    @recipe = current_user.recipes.find(params[:id])
  end

  def update
    @recipe = current_user.recipes.find(params[:id])
    if @recipe.update(recipe_params)
      redirect_to recipes_path
    else
      render :edit    
    end
  end

  #Ajax add ingredient
  def add_ingredient
    @recipe = Recipe.new
    ingredient = @recipe.ingredients.new
    ingredient.ingredients_lists.new
    render "add_ingredient", :layout => false  
  end

  #Ajax add step
  def add_step
    @recipe = Recipe.new
    step = @recipe.steps.new
    render "add_step", :layout => false
  end

  private
  def recipe_params
    params.require(:recipe).permit(
                                    :name,
                                    :description,
                                    :time,
                                    :quantity,
                                    :image,
                                    steps_attributes: [:image, :sequence, :description],
                                    ingredients_attributes: [:name, ingredients_lists_attributes: [:amount]]
                                    
                                  )
  end  

  def pick_ingredients_lists_params
    # 取得ingredient_list參數
    list_params_array = recipe_params[:ingredients_attributes].values.map{|a| a[:ingredients_lists_attributes].values[0][:amount]}
    return list_params_array
  end

  def delete_list_params(params)
    output = params
    output[:ingredients_attributes].values.map{|i| i.delete(:ingredients_lists_attributes)}
    output
  end

  def set_all_ingredient_amount(recipe, list_params_array)
    ids_array = recipe.ingredients.ids
    i = 0
    while i < ids_array.length
      list = recipe.ingredients_lists.find_by(ingredient_id: ids_array[i])
      list.amount = list_params_array[i]
      list.save
      i += 1
    end
  end
end

app/controllers/steps_controller.rb
class StepsController < ApplicationController

  def index
    @recipe = current_user.recipes.find(params[:recipe_id])
    @steps = @recipe.steps
  end

  def new
    @step = Step.new
  end

  def create
    @step = current_user.recipes.find(params[:recipe_id]).steps.build(step_params)
    if @step.save
      redirect_to recipe_steps_path
    else
      render :new
    end
  end

  def destroy
    step = current_user.recipes.find(params[:recipe_id]).steps.find(params[:id])
    step.destroy
    redirect_to recipe_steps_path
  end

  def edit
    @step = current_user.steps.find(params[:id])
  end

  def update
    step = current_user.recipes.find(params[:recipe_id]).steps.find(params[:id])
    if step.update(step_params)
      redirect_to recipe_steps_path
    else
      render :edit
    end
  end

  private
  def step_params
    params.require(:step).permit( :image, 
                                  :description, 
                                  :sequence,
                                  :recipe_id, 
                                  :user_id
                                )
    
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/homepage_helper.rb
module HomepageHelper
end

app/helpers/ingredients_helper.rb
module IngredientsHelper
end

app/helpers/recipes_helper.rb
module RecipesHelper
end

app/helpers/steps_helper.rb
module StepsHelper
end

app/views/home/index.html.erb
<div class="show_recipes_place">
  <% @recipes.each do |recipe| %>
    <div class="recipe_item">
      <%= link_to recipe_path(recipe.id) do %>
        <%= image_tag recipe.image.middle.url %>
      <% end %>
    </div>
  <% end %>  
</div>

app/views/ingredients/index.html.erb
<%= link_to "新增食材", new_ingredient_path %>
<% @ingredients.each do |ingredient| %>
  <div>
    <%= link_to ingredient.name, ingredient_path(ingredient.id) %>
    <%= link_to "編輯", edit_ingredient_path(ingredient.id) %>
    <%= link_to "刪除", ingredient_path(ingredient.id), method: "delete" %>
  </div>  
<% end %>

app/views/ingredients/new.html.erb
<%= form_for @ingredient do |f| %>
  <div class="form_section">
    <%= f.label "食材名稱", class:"form-label" %>
    <%= f.text_field :name, class: "form-control"%>
  </div>
  <%= f.submit "建立" %>
<% end %>    

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MyMenu</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <%= render "shared/navbar" %>
  <%= render "shared/flash" %>
  <div class="container">
    <%= yield %>
  </div>
  </body>
</html>

app/views/layouts/homepage.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MyMenu</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <%= render "shared/navbar" %>
  <%= render "shared/flash" %>
  <div class="container main_bg">
    <%= yield %>
  </div>
  </body>
</html>

app/views/recipes/_form.html.erb

<%= form_for recipe do |f| %>
  <div class="form_section">
    <%= f.label "食譜名稱", class:"form-label form_title" %>
    <%= f.text_field :name, class: "form-control"%>
  </div>
  <div class="form_section" data-controller="form" >
    <%= f.label "圖片", class:"form-label form_title" %>
      <div class="upload_section">
        <label>
          <% if recipe.image? %>
            <%= image_tag recipe.image.thumb.url, class: "recipe_img"%>
          <% else %>
            <%= image_tag "cat.png", class: "default_image", "data-target" => "form.recipe_img" %>
          <% end %>
          <%= f.file_field :image, class: "d-none", "data-target" => "form.img_input", "data-action" => "change->form#upload_preview" %>
        </label>
      </div>
  </div>
  <div class="form_section">
    <%= f.label "簡介", class:"form-label form_title" %>
    <%= f.text_area :description, class: "form-control", rows: "3" %>
  </div>
  <div class="form_section">
    <%= f.label "所需時間(分鐘)", class:"form-label form_title" %>
    <%= f.text_field :time, class: "form-control" %>
  </div>
  <div class="form_section">
    <%= f.label "份量(人份)", class:"form-label form_title" %>
    <%= f.text_field :quantity, class: "form-control" %>
  </div>
  <%= f.fields_for :ingredients do |af| %>
    <div class="form_section">
      <%= af.label "食材", class:"form-label form_title" %>
      <div class="ingredient_input">
        <%= af.text_field :name, placeholder: "食材", class: "form-control" %>
        <%= af.fields_for :ingredients_lists do |aaf| %>
            <%= aaf.text_field :amount, placeholder: "份量", class: "form-control" %>
        <% end %>
      </div>
    </div>
  <% end %>
  <div class="form_section" >
    <%= f.label "步驟", class:"form-label form_title" %>
    <%= f.fields_for :steps do |ff| %>
      <div class="step_form_group" data-controller="form">
        <div class="step_image_upload_section">
          <label>
            <%= image_tag "cat.png", class: "step_default_image", "data-target" => "form.recipe_img" %>
            <%= ff.file_field :image, class: "d-none", "data-target" => "form.img_input", "data-action" => "change->form#upload_preview" %>
          </label>
        </div>
        <div class="step_description_section">
          <%= ff.text_field :sequence, class: "form-control step_sequence" %>
          <%= ff.text_area :description, class: "form-control step_description"%>
        </div>
      </div>
    <% end %>
  </div>

  <%= f.submit "建立" %>
<% end %>    

app/views/recipes/_ingredient_field.html.erb
<%= f.fields_for :ingredients, :child_index => child_index do |af| %>

    <div class="ingredient_input">
      <%= af.text_field :name, placeholder: "食材", class: "form-control" %>
      <%= af.fields_for :ingredients_lists do |aaf| %>
          <%= aaf.text_field :amount, placeholder: "份量", class: "form-control" %>
      <% end %>
      <button class=" delete_ingredient_btn btn btn-outline-dark" data-action="click->form#delete_ingredient" data-target="form.delete_ingredient_btn">
        <i class="fas fa-trash"></i>
      </button>
    </div>
<% end %>

app/views/recipes/_step_field.html.erb
<%= f.fields_for :steps, :child_index => child_index do |ff| %>
  <div class="step_form_group" data-controller="form">
    <div class="step_image_upload_section">
      <label>
        <%= image_tag "cat.png", class: "step_default_image", "data-target" => "form.recipe_img" %>
        <%= ff.file_field :image, class: "d-none", "data-target" => "form.img_input", "data-action" => "change->form#upload_preview" %>
      </label>
    </div>
    <div class="step_description_section">
      <h1 class="step_sequence">1</h1>
      <%= ff.hidden_field :sequence, class: "form-control step_sequence_input" %>
      <%= ff.text_area :description, class: "form-control step_description"%>
    </div>
    <button class=" delete_step_btn btn btn-outline-dark" data-action="click->form#delete_step" data-target="form.delete_step_btn">
      <i class="fas fa-trash"></i>
    </button>
  </div>
<% end %>

app/views/recipes/add_ingredient.html.erb
<%= form_for @recipe, :url => recipes_path, :authenticity_token => false do |f| %>
  <% render :partial => "ingredient_field", locals: {f: f, child_index: Time.now.to_i} %>
<% end %> 

app/views/recipes/add_step.html.erb
<%= form_for @recipe, :url => recipes_path, :authenticity_token => false do |f| %>
  <% render :partial => "step_field", locals: {f: f, child_index: Time.now.to_i} %>
<% end %> 

app/views/recipes/edit.html.erb
<h1>編輯食譜</h1>
<%= render "form", recipe: @recipe %>

app/views/recipes/index.html.erb
<h1>食譜</h1>
<%= link_to "新增", new_recipe_path %>
<% @recipes.each do |recipe| %>
  <div>
    <%= image_tag recipe.image.thumb.url if recipe.image?  %>
    <%= link_to recipe.name, recipe_path(recipe.id) %>
    <%= link_to "步驟", recipe_steps_path(recipe.id) %>
    <%= link_to "編輯", edit_recipe_path(recipe.id) %>
    <%= link_to "刪除", recipe_path(recipe.id), method: :delete %>
  </div>  
<% end %>


app/views/recipes/new.html.erb
<div class="recipe_form" data-controller="form">
  <%= form_for @recipe do |f| %>
    <div class="form_section">
      <%= f.label "食譜名稱", class:"form-label form_title" %>
      <%= f.text_field :name, class: "form-control" %>
    </div>
    <div class="form_section" data-controller="form" >
      <%= f.label "圖片", class:"form-label form_title" %>
        <div class="upload_section">
          <label>
            <% if @recipe.image? %>
              <%= image_tag @recipe.image.thumb.url, class: "recipe_img"%>
            <% else %>
              <%= image_tag "cat.png", class: "default_image", "data-target" => "form.recipe_img" %>
            <% end %>
            <%= f.file_field :image, class: "d-none", "data-target" => "form.img_input", "data-action" => "change->form#upload_preview" %>
          </label>
        </div>
    </div>
    <div class="form_section">
      <%= f.label "簡介", class:"form-label form_title" %>
      <%= f.text_area :description, class: "form-control", rows: "3" %>
    </div>
    <div class="form_section">
      <%= f.label "所需時間(分鐘)", class:"form-label form_title" %>
      <%= f.text_field :time, class: "form-control" %>
    </div>
    <div class="form_section">
      <%= f.label "份量(人份)", class:"form-label form_title" %>
      <%= f.text_field :quantity, class: "form-control" %>
    </div>
    <div class="ingredient_section" >
      <div class="form_section">
        <%= f.label "食材", class:"form-label form_title" %>
        <%= render :partial => "ingredient_field", locals: {f: f, child_index: Time.now.to_i} %>
      </div>
      <div class="add_ingredient_section">
        <button class="add_ingredient_btn btn btn-outline-dark" data-target="form.add_ingredient_btn" data-action="click -> form#add_ingredient">
          <i class="fas fa-plus"></i>
        </button>
      </div>
    </div>
    <div class="step_section" >
      <div class="form_section" >
        <%= f.label "步驟", class:"form-label form_title" %>
        <%= render :partial => "step_field", locals: {f: f, child_index: Time.now.to_i} %>
      </div>
      <div class="add_step_section">
        <button class="add_step_btn btn btn-outline-dark" data-target="form.add_step_btn" data-action="click -> form#add_step">
          <i class="fas fa-plus"></i>
        </button>
      </div>
    </div>

    <%= f.submit "建立" %>
  <% end %>    
</div>

app/views/recipes/show.html.erb
<div class="recipe_info_group">
  <%= image_tag @recipe.image.big.url, class: "recipe_image"%>
  <h1 class="recipe_title"><%= @recipe.name %></h1> 
  <p class="recipe_description"><%= @recipe.description %></p>
</div>
<div class="recipe_time">
  <p>所需時間</p>
  <%= @recipe.time %>分
</div>
<div class="recipe_quantity">
  <p>份量</p>
  <%= @recipe.time %>人份
</div>
<div class="recipe_ingredients">
  <p>食材</p>
  <% @ingredients_lists.each do |list| %>
    <span class="ingredient"><%= list.ingredient.name %><%= list.amount %></span>
  <% end %>
</div>
<div class="recipe_steps">
  <% @recipe.steps.each do |step| %>
  <div class="step_item">
    <div class="step_instruction">
      <div class="step_image">
        <%= image_tag step.image.thumb.url if step.image? %>
      </div>
      <div class="step_info">
        <h1 class="step_sequence"><%= step.sequence %></h1>
        <section class="step_description"><%= step.description %></section>
      </div>
    </div>
  </div>

  <% end %>
</div>

app/views/shared/_flash.html.erb
<%if alert %>
  <%= alert %>
<% end %> 
<%if notice %>
  <%= notice %>
<% end %> 

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container-fluid">
    <%= link_to "料理貓", root_path, class: "navbar-brand" %>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav mb-2 mb-lg-0">
      <% if current_user %>
        <li class="nav-item">
          <%= link_to new_recipe_path, class: "nav-link" do %>
            <p class="recipe_new">
              新增食譜
              <i class="far fa-plus-square"></i>
            </p>
          <% end %>
        </li>
        <li class="nav-item">
          <%= link_to current_user.email, "#", class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to '登出', destroy_user_session_path, method: 'delete', class: 'nav-link' %>
        </li>
      <% else %>
        <li class="nav-item">
          <%= link_to '登入', new_user_session_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to '註冊', new_user_registration_path, class: "nav-link" %>
        </li>
      <% end %>
      </ul>
    </div>
  </div>
</nav>

app/views/steps/_form.html.erb
<%= form_for step, url: recipe_steps_path, action: "create" do |f| %>
  <div>
    <%= f.label "圖片" %>
    <%= image_tag step.image.thumb.url if step.image? %>
      <label class="btn btn-info" style="width: 50px; height: 50px;">
        <%= f.file_field :image, class: "d-none" %>
      </label>
  </div>
  <div>
    <%= f.label "步驟" %>
    <%= f.text_field :sequence %>
  </div>
  <div>
    <%= f.label "描述" %>
    <%= f.text_field :description %>
  </div>
  <%= f.submit "建立", value: "Submit" %>
<% end %>    

app/views/steps/edit.html.erb
<%= form_for @step, url: recipe_step_path, action: "update", html: {method: "patch"} do |f| %>
  <div>
    <%= f.label "圖片" %>
      <label class="btn btn-info" style="width: 50px; height: 50px;">
        <%= f.file_field :image, class: "d-none" %>
      </label>
  </div>
  <div>
    <%= f.label "步驟" %>
    <%= f.text_field :sequence %>
  </div>
  <div>
    <%= f.label "描述" %>
    <%= f.text_field :description %>
  </div>
  <%= f.submit "建立", value: "Submit" %>
<% end %>     

app/views/steps/index.html.erb
<%= link_to "新增", new_recipe_step_path %>
<% @steps.each do |step| %>
  <div>
    <%= image_tag step.image.thumb.url if step.image? %>
    <%= step.description %>
    <%= step.sequence %>
    <%= link_to "編輯", edit_recipe_step_path(step.recipe_id, step.id) %>
    <%= link_to "刪除", recipe_step_path(step.recipe_id,step.id), method: "delete" %>
  </div>
<% end %>

app/views/steps/new.html.erb
<%= render "form", step: @step %>